# This is a basic workflow to help you get started with Actions

name: lk2nd build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y device-tree-compiler gcc-arm-none-eabi git libfdt-dev curl
    - name: Downloading source code
      run: |
        git clone https://github.com/Android-Boot-Manager/droidboot_device_motorola_cedric ~/droidboot_device_motorola_cedric
    - name: Build 
      run: |
        cd ~/droidboot_device_motorola_cedric
        make TOOLCHAIN_PREFIX=arm-none-eabi- msm8952-secondary
    - name : Upload boot image
      uses: actions/upload-artifact@master
      with:
        name: lk2nd image
        path: /home/runner/droidboot_device_motorola_cedric/build-msm8952-secondary/lk2nd.img
    - name: send custom message
      env:
        TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: | 
        curl -s "https://api.telegram.org/bot$TOKEN/sendMessage?chat_id=-1001367413201&text=New lk2nd build for Moto G5 cedric is ready. Check it here https://github.com/Android-Boot-Manager/droidboot_device_motorola_cedric/actions/runs/$GITHUB_RUN_ID"
     
